// Mocks generated by Mockito 5.4.6 from annotations
// in frontend_mobile_nodos_app/test/app_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i17;

import 'package:flutter_bloc/flutter_bloc.dart' as _i19;
import 'package:frontend_mobile_nodos_app/features/ble/domain/repositories/ble_repository.dart'
    as _i2;
import 'package:frontend_mobile_nodos_app/features/ble/presentation/bloc/ble_bloc.dart'
    as _i16;
import 'package:frontend_mobile_nodos_app/features/ble/presentation/bloc/ble_event.dart'
    as _i18;
import 'package:frontend_mobile_nodos_app/features/ble/presentation/bloc/ble_state.dart'
    as _i3;
import 'package:frontend_mobile_nodos_app/features/history/domain/usecases/get_history_stats.dart'
    as _i14;
import 'package:frontend_mobile_nodos_app/features/history/domain/usecases/get_scan_sessions.dart'
    as _i12;
import 'package:frontend_mobile_nodos_app/features/history/domain/usecases/get_session_detail.dart'
    as _i13;
import 'package:frontend_mobile_nodos_app/features/history/presentation/bloc/history_bloc.dart'
    as _i15;
import 'package:frontend_mobile_nodos_app/features/nodes/domain/usecases/observe_nodes.dart'
    as _i4;
import 'package:frontend_mobile_nodos_app/features/nodes/domain/usecases/update_node_metadata.dart'
    as _i5;
import 'package:frontend_mobile_nodos_app/features/nodes/presentation/bloc/node_list_bloc.dart'
    as _i6;
import 'package:frontend_mobile_nodos_app/features/user/domain/usecases/get_user_profile.dart'
    as _i7;
import 'package:frontend_mobile_nodos_app/features/user/domain/usecases/update_user_color.dart'
    as _i9;
import 'package:frontend_mobile_nodos_app/features/user/domain/usecases/update_user_name.dart'
    as _i8;
import 'package:frontend_mobile_nodos_app/features/user/presentation/bloc/user_bloc.dart'
    as _i10;
import 'package:frontend_mobile_nodos_app/features/visualization/presentation/bloc/visualization_bloc.dart'
    as _i20;
import 'package:frontend_mobile_nodos_app/features/visualization/presentation/bloc/visualization_event.dart'
    as _i21;
import 'package:frontend_mobile_nodos_app/features/visualization/presentation/bloc/visualization_state.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBleRepository_0 extends _i1.SmartFake implements _i2.BleRepository {
  _FakeBleRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBleState_1 extends _i1.SmartFake implements _i3.BleState {
  _FakeBleState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeObserveNodes_2 extends _i1.SmartFake implements _i4.ObserveNodes {
  _FakeObserveNodes_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateNodeMetadata_3 extends _i1.SmartFake
    implements _i5.UpdateNodeMetadata {
  _FakeUpdateNodeMetadata_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNodeListState_4 extends _i1.SmartFake implements _i6.NodeListState {
  _FakeNodeListState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetUserProfile_5 extends _i1.SmartFake
    implements _i7.GetUserProfile {
  _FakeGetUserProfile_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateUserName_6 extends _i1.SmartFake
    implements _i8.UpdateUserName {
  _FakeUpdateUserName_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateUserColor_7 extends _i1.SmartFake
    implements _i9.UpdateUserColor {
  _FakeUpdateUserColor_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserState_8 extends _i1.SmartFake implements _i10.UserState {
  _FakeUserState_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVisualizationState_9 extends _i1.SmartFake
    implements _i11.VisualizationState {
  _FakeVisualizationState_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetScanSessions_10 extends _i1.SmartFake
    implements _i12.GetScanSessions {
  _FakeGetScanSessions_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetSessionDetail_11 extends _i1.SmartFake
    implements _i13.GetSessionDetail {
  _FakeGetSessionDetail_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetHistoryStats_12 extends _i1.SmartFake
    implements _i14.GetHistoryStats {
  _FakeGetHistoryStats_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHistoryState_13 extends _i1.SmartFake implements _i15.HistoryState {
  _FakeHistoryState_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BleBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleBloc extends _i1.Mock implements _i16.BleBloc {
  @override
  _i2.BleRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeBleRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeBleRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.BleRepository);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.BleState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeBleState_1(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeBleState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.BleState);

  @override
  _i17.Stream<_i3.BleState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i17.Stream<_i3.BleState>.empty(),
            returnValueForMissingStub: _i17.Stream<_i3.BleState>.empty(),
          )
          as _i17.Stream<_i3.BleState>);

  @override
  _i17.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  void add(_i18.BleEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i18.BleEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.BleState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i18.BleEvent>(
    _i19.EventHandler<E, _i3.BleState>? handler, {
    _i19.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(_i19.Transition<_i18.BleEvent, _i3.BleState>? transition) =>
      super.noSuchMethod(
        Invocation.method(#onTransition, [transition]),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(_i18.BleEvent? event, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#onDone, [event, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i19.Change<_i3.BleState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NodeListBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeListBloc extends _i1.Mock implements _i6.NodeListBloc {
  @override
  _i4.ObserveNodes get observeNodes =>
      (super.noSuchMethod(
            Invocation.getter(#observeNodes),
            returnValue: _FakeObserveNodes_2(
              this,
              Invocation.getter(#observeNodes),
            ),
            returnValueForMissingStub: _FakeObserveNodes_2(
              this,
              Invocation.getter(#observeNodes),
            ),
          )
          as _i4.ObserveNodes);

  @override
  _i5.UpdateNodeMetadata get updateNodeMetadata =>
      (super.noSuchMethod(
            Invocation.getter(#updateNodeMetadata),
            returnValue: _FakeUpdateNodeMetadata_3(
              this,
              Invocation.getter(#updateNodeMetadata),
            ),
            returnValueForMissingStub: _FakeUpdateNodeMetadata_3(
              this,
              Invocation.getter(#updateNodeMetadata),
            ),
          )
          as _i5.UpdateNodeMetadata);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.NodeListState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeNodeListState_4(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeNodeListState_4(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i6.NodeListState);

  @override
  _i17.Stream<_i6.NodeListState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i17.Stream<_i6.NodeListState>.empty(),
            returnValueForMissingStub: _i17.Stream<_i6.NodeListState>.empty(),
          )
          as _i17.Stream<_i6.NodeListState>);

  @override
  _i17.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  void add(_i6.NodeListEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i6.NodeListEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i6.NodeListState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i6.NodeListEvent>(
    _i19.EventHandler<E, _i6.NodeListState>? handler, {
    _i19.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i19.Transition<_i6.NodeListEvent, _i6.NodeListState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i6.NodeListEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i19.Change<_i6.NodeListState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserBloc extends _i1.Mock implements _i10.UserBloc {
  @override
  _i7.GetUserProfile get getProfile =>
      (super.noSuchMethod(
            Invocation.getter(#getProfile),
            returnValue: _FakeGetUserProfile_5(
              this,
              Invocation.getter(#getProfile),
            ),
            returnValueForMissingStub: _FakeGetUserProfile_5(
              this,
              Invocation.getter(#getProfile),
            ),
          )
          as _i7.GetUserProfile);

  @override
  _i8.UpdateUserName get updateName =>
      (super.noSuchMethod(
            Invocation.getter(#updateName),
            returnValue: _FakeUpdateUserName_6(
              this,
              Invocation.getter(#updateName),
            ),
            returnValueForMissingStub: _FakeUpdateUserName_6(
              this,
              Invocation.getter(#updateName),
            ),
          )
          as _i8.UpdateUserName);

  @override
  _i9.UpdateUserColor get updateColor =>
      (super.noSuchMethod(
            Invocation.getter(#updateColor),
            returnValue: _FakeUpdateUserColor_7(
              this,
              Invocation.getter(#updateColor),
            ),
            returnValueForMissingStub: _FakeUpdateUserColor_7(
              this,
              Invocation.getter(#updateColor),
            ),
          )
          as _i9.UpdateUserColor);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.UserState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeUserState_8(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeUserState_8(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i10.UserState);

  @override
  _i17.Stream<_i10.UserState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i17.Stream<_i10.UserState>.empty(),
            returnValueForMissingStub: _i17.Stream<_i10.UserState>.empty(),
          )
          as _i17.Stream<_i10.UserState>);

  @override
  void add(_i10.UserEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i10.UserEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i10.UserState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i10.UserEvent>(
    _i19.EventHandler<E, _i10.UserState>? handler, {
    _i19.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i19.Transition<_i10.UserEvent, _i10.UserState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(_i10.UserEvent? event, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#onDone, [event, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  _i17.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  void onChange(_i19.Change<_i10.UserState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [VisualizationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockVisualizationBloc extends _i1.Mock implements _i20.VisualizationBloc {
  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i11.VisualizationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeVisualizationState_9(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeVisualizationState_9(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i11.VisualizationState);

  @override
  _i17.Stream<_i11.VisualizationState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i17.Stream<_i11.VisualizationState>.empty(),
            returnValueForMissingStub:
                _i17.Stream<_i11.VisualizationState>.empty(),
          )
          as _i17.Stream<_i11.VisualizationState>);

  @override
  void add(_i21.VisualizationEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i21.VisualizationEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i11.VisualizationState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i21.VisualizationEvent>(
    _i19.EventHandler<E, _i11.VisualizationState>? handler, {
    _i19.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i19.Transition<_i21.VisualizationEvent, _i11.VisualizationState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i21.VisualizationEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i17.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  void onChange(_i19.Change<_i11.VisualizationState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [HistoryBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryBloc extends _i1.Mock implements _i15.HistoryBloc {
  @override
  _i12.GetScanSessions get getScanSessions =>
      (super.noSuchMethod(
            Invocation.getter(#getScanSessions),
            returnValue: _FakeGetScanSessions_10(
              this,
              Invocation.getter(#getScanSessions),
            ),
            returnValueForMissingStub: _FakeGetScanSessions_10(
              this,
              Invocation.getter(#getScanSessions),
            ),
          )
          as _i12.GetScanSessions);

  @override
  _i13.GetSessionDetail get getSessionDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getSessionDetail),
            returnValue: _FakeGetSessionDetail_11(
              this,
              Invocation.getter(#getSessionDetail),
            ),
            returnValueForMissingStub: _FakeGetSessionDetail_11(
              this,
              Invocation.getter(#getSessionDetail),
            ),
          )
          as _i13.GetSessionDetail);

  @override
  _i14.GetHistoryStats get getHistoryStats =>
      (super.noSuchMethod(
            Invocation.getter(#getHistoryStats),
            returnValue: _FakeGetHistoryStats_12(
              this,
              Invocation.getter(#getHistoryStats),
            ),
            returnValueForMissingStub: _FakeGetHistoryStats_12(
              this,
              Invocation.getter(#getHistoryStats),
            ),
          )
          as _i14.GetHistoryStats);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i15.HistoryState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeHistoryState_13(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeHistoryState_13(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i15.HistoryState);

  @override
  _i17.Stream<_i15.HistoryState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i17.Stream<_i15.HistoryState>.empty(),
            returnValueForMissingStub: _i17.Stream<_i15.HistoryState>.empty(),
          )
          as _i17.Stream<_i15.HistoryState>);

  @override
  void add(_i15.HistoryEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i15.HistoryEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i15.HistoryState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i15.HistoryEvent>(
    _i19.EventHandler<E, _i15.HistoryState>? handler, {
    _i19.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i19.Transition<_i15.HistoryEvent, _i15.HistoryState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i15.HistoryEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i17.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  void onChange(_i19.Change<_i15.HistoryState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
