// Mocks generated by Mockito 5.4.6 from annotations
// in frontend_mobile_nodos_app/test/features/visualization/domain/usecases/build_graph_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:frontend_mobile_nodos_app/features/visualization/domain/entities/graph_edge.dart'
    as _i5;
import 'package:frontend_mobile_nodos_app/features/visualization/domain/entities/layout_result.dart'
    as _i2;
import 'package:frontend_mobile_nodos_app/features/visualization/domain/repositories/graph_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLayoutResult_0 extends _i1.SmartFake implements _i2.LayoutResult {
  _FakeLayoutResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GraphRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockGraphRepository extends _i1.Mock implements _i3.GraphRepository {
  @override
  _i4.Future<_i2.LayoutResult> buildGraph(
    int? scanSessionId, {
    String? myDeviceUuid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #buildGraph,
              [scanSessionId],
              {#myDeviceUuid: myDeviceUuid},
            ),
            returnValue: _i4.Future<_i2.LayoutResult>.value(
              _FakeLayoutResult_0(
                this,
                Invocation.method(
                  #buildGraph,
                  [scanSessionId],
                  {#myDeviceUuid: myDeviceUuid},
                ),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.LayoutResult>.value(
              _FakeLayoutResult_0(
                this,
                Invocation.method(
                  #buildGraph,
                  [scanSessionId],
                  {#myDeviceUuid: myDeviceUuid},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.LayoutResult>);

  @override
  _i4.Future<List<_i5.GraphEdge>> getEdges(int? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#getEdges, [sessionId]),
            returnValue: _i4.Future<List<_i5.GraphEdge>>.value(
              <_i5.GraphEdge>[],
            ),
            returnValueForMissingStub: _i4.Future<List<_i5.GraphEdge>>.value(
              <_i5.GraphEdge>[],
            ),
          )
          as _i4.Future<List<_i5.GraphEdge>>);
}
