// Mocks generated by Mockito 5.4.6 from annotations
// in frontend_mobile_nodos_app/test/features/ble/data/repositories/ble_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:frontend_mobile_nodos_app/features/ble/data/datasources/ble_advertiser_datasource.dart'
    as _i5;
import 'package:frontend_mobile_nodos_app/features/ble/data/datasources/ble_scanner_datasource.dart'
    as _i2;
import 'package:frontend_mobile_nodos_app/features/ble/domain/entities/ble_device.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [BleScannerDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleScannerDataSource extends _i1.Mock
    implements _i2.BleScannerDataSource {
  @override
  _i3.Stream<List<_i4.BleDevice>> get scanResults =>
      (super.noSuchMethod(
            Invocation.getter(#scanResults),
            returnValue: _i3.Stream<List<_i4.BleDevice>>.empty(),
            returnValueForMissingStub: _i3.Stream<List<_i4.BleDevice>>.empty(),
          )
          as _i3.Stream<List<_i4.BleDevice>>);

  @override
  _i3.Stream<bool> get bluetoothState =>
      (super.noSuchMethod(
            Invocation.getter(#bluetoothState),
            returnValue: _i3.Stream<bool>.empty(),
            returnValueForMissingStub: _i3.Stream<bool>.empty(),
          )
          as _i3.Stream<bool>);

  @override
  _i3.Future<void> startScan({List<String>? serviceUuids}) =>
      (super.noSuchMethod(
            Invocation.method(#startScan, [], {#serviceUuids: serviceUuids}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopScan() =>
      (super.noSuchMethod(
            Invocation.method(#stopScan, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BleAdvertiserDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleAdvertiserDataSource extends _i1.Mock
    implements _i5.BleAdvertiserDataSource {
  @override
  _i3.Future<void> startAdvertise(
    String? deviceUuid,
    String? name,
    String? color,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startAdvertise, [deviceUuid, name, color]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopAdvertise() =>
      (super.noSuchMethod(
            Invocation.method(#stopAdvertise, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
