// Mocks generated by Mockito 5.4.6 from annotations
// in frontend_mobile_nodos_app/test/features/visualization/presentation/bloc/visualization_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i2;
import 'package:frontend_mobile_nodos_app/core/errors/failures.dart' as _i6;
import 'package:frontend_mobile_nodos_app/features/visualization/domain/algorithms/layout_algorithm.dart'
    as _i3;
import 'package:frontend_mobile_nodos_app/features/visualization/domain/entities/layout_result.dart'
    as _i7;
import 'package:frontend_mobile_nodos_app/features/visualization/domain/usecases/build_graph.dart'
    as _i4;
import 'package:frontend_mobile_nodos_app/features/visualization/domain/usecases/calculate_layout.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLayoutAlgorithm_1 extends _i1.SmartFake
    implements _i3.LayoutAlgorithm {
  _FakeLayoutAlgorithm_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BuildGraph].
///
/// See the documentation for Mockito's code generation for more information.
class MockBuildGraph extends _i1.Mock implements _i4.BuildGraph {
  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.LayoutResult>> call(
    int? scanSessionId, {
    String? myDeviceUuid,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #call,
              [scanSessionId],
              {#myDeviceUuid: myDeviceUuid},
            ),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i7.LayoutResult>>.value(
                  _FakeEither_0<_i6.Failure, _i7.LayoutResult>(
                    this,
                    Invocation.method(
                      #call,
                      [scanSessionId],
                      {#myDeviceUuid: myDeviceUuid},
                    ),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.Either<_i6.Failure, _i7.LayoutResult>>.value(
                  _FakeEither_0<_i6.Failure, _i7.LayoutResult>(
                    this,
                    Invocation.method(
                      #call,
                      [scanSessionId],
                      {#myDeviceUuid: myDeviceUuid},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i7.LayoutResult>>);
}

/// A class which mocks [CalculateLayout].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalculateLayout extends _i1.Mock implements _i8.CalculateLayout {
  @override
  _i3.LayoutAlgorithm get layoutAlgorithm =>
      (super.noSuchMethod(
            Invocation.getter(#layoutAlgorithm),
            returnValue: _FakeLayoutAlgorithm_1(
              this,
              Invocation.getter(#layoutAlgorithm),
            ),
            returnValueForMissingStub: _FakeLayoutAlgorithm_1(
              this,
              Invocation.getter(#layoutAlgorithm),
            ),
          )
          as _i3.LayoutAlgorithm);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.LayoutResult>> call(
    _i7.LayoutResult? layout,
    double? width,
    double? height, {
    double? depth = 0.0,
    _i7.LayoutResult? priorLayout,
    int? seed,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #call,
              [layout, width, height],
              {#depth: depth, #priorLayout: priorLayout, #seed: seed},
            ),
            returnValue:
                _i5.Future<_i2.Either<_i6.Failure, _i7.LayoutResult>>.value(
                  _FakeEither_0<_i6.Failure, _i7.LayoutResult>(
                    this,
                    Invocation.method(
                      #call,
                      [layout, width, height],
                      {#depth: depth, #priorLayout: priorLayout, #seed: seed},
                    ),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<_i2.Either<_i6.Failure, _i7.LayoutResult>>.value(
                  _FakeEither_0<_i6.Failure, _i7.LayoutResult>(
                    this,
                    Invocation.method(
                      #call,
                      [layout, width, height],
                      {#depth: depth, #priorLayout: priorLayout, #seed: seed},
                    ),
                  ),
                ),
          )
          as _i5.Future<_i2.Either<_i6.Failure, _i7.LayoutResult>>);
}
