// Mocks generated by Mockito from annotations
// in frontend_mobile_nodos_app/test/features/ble/presentation/services/ble_lifecycle_coordinator_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;
import 'dart:typed_data' as _i6;

import 'package:frontend_mobile_nodos_app/features/ble/domain/entities/ble_device.dart'
    as _i5;
import 'package:frontend_mobile_nodos_app/features/ble/domain/entities/nodos_graph_payload.dart'
    as _i2;
import 'package:frontend_mobile_nodos_app/features/ble/domain/repositories/ble_connection_repository.dart'
    as _i7;
import 'package:frontend_mobile_nodos_app/features/ble/domain/repositories/ble_repository.dart'
    as _i3;
import 'package:frontend_mobile_nodos_app/features/ble/domain/services/active_graph_exchange_service.dart'
    as _i12;
import 'package:frontend_mobile_nodos_app/features/nodes/domain/entities/node.dart'
    as _i9;
import 'package:frontend_mobile_nodos_app/features/nodes/domain/repositories/node_repository.dart'
    as _i8;
import 'package:frontend_mobile_nodos_app/features/user/domain/entities/user.dart'
    as _i11;
import 'package:frontend_mobile_nodos_app/features/user/domain/repositories/user_repository.dart'
    as _i10;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNodosGraphPayload_0 extends _i1.SmartFake
    implements _i2.NodosGraphPayload {
  _FakeNodosGraphPayload_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleRepository extends _i1.Mock implements _i3.BleRepository {
  @override
  _i4.Stream<List<_i5.BleDevice>> get scanResults =>
      (super.noSuchMethod(
            Invocation.getter(#scanResults),
            returnValue: _i4.Stream<List<_i5.BleDevice>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<_i5.BleDevice>>.empty(),
          )
          as _i4.Stream<List<_i5.BleDevice>>);

  @override
  _i4.Stream<_i3.BleIncomingGattWrite> get incomingLinkRequests =>
      (super.noSuchMethod(
            Invocation.getter(#incomingLinkRequests),
            returnValue: _i4.Stream<_i3.BleIncomingGattWrite>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i3.BleIncomingGattWrite>.empty(),
          )
          as _i4.Stream<_i3.BleIncomingGattWrite>);

  @override
  _i4.Stream<_i3.BleIncomingGattWrite> get incomingPeerGraphPayloads =>
      (super.noSuchMethod(
            Invocation.getter(#incomingPeerGraphPayloads),
            returnValue: _i4.Stream<_i3.BleIncomingGattWrite>.empty(),
            returnValueForMissingStub:
                _i4.Stream<_i3.BleIncomingGattWrite>.empty(),
          )
          as _i4.Stream<_i3.BleIncomingGattWrite>);

  @override
  _i4.Stream<bool> get bluetoothState =>
      (super.noSuchMethod(
            Invocation.getter(#bluetoothState),
            returnValue: _i4.Stream<bool>.empty(),
            returnValueForMissingStub: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);

  @override
  _i4.Future<void> startScan() =>
      (super.noSuchMethod(
            Invocation.method(#startScan, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopScan() =>
      (super.noSuchMethod(
            Invocation.method(#stopScan, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> startAdvertise(
    String? deviceUuid,
    String? name,
    String? color,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#startAdvertise, [deviceUuid, name, color]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateGraphPayload(_i6.Uint8List? payload) =>
      (super.noSuchMethod(
            Invocation.method(#updateGraphPayload, [payload]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> sendLinkResponse(_i6.Uint8List? payload) =>
      (super.noSuchMethod(
            Invocation.method(#sendLinkResponse, [payload]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopAdvertise() =>
      (super.noSuchMethod(
            Invocation.method(#stopAdvertise, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> endScanSession() =>
      (super.noSuchMethod(
            Invocation.method(#endScanSession, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [BleConnectionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleConnectionRepository extends _i1.Mock
    implements _i7.BleConnectionRepository {
  @override
  _i4.Future<void> connect(String? remoteId) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [remoteId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> disconnect(String? remoteId) =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, [remoteId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<bool> connectionState(String? remoteId) =>
      (super.noSuchMethod(
            Invocation.method(#connectionState, [remoteId]),
            returnValue: _i4.Stream<bool>.empty(),
            returnValueForMissingStub: _i4.Stream<bool>.empty(),
          )
          as _i4.Stream<bool>);

  @override
  _i4.Future<void> discoverServices(String? remoteId) =>
      (super.noSuchMethod(
            Invocation.method(#discoverServices, [remoteId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<int>?> readCharacteristic(
    String? remoteId,
    String? characteristicUuid,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#readCharacteristic, [
              remoteId,
              characteristicUuid,
            ]),
            returnValue: _i4.Future<List<int>?>.value(),
            returnValueForMissingStub: _i4.Future<List<int>?>.value(),
          )
          as _i4.Future<List<int>?>);

  @override
  _i4.Future<bool> writeCharacteristic(
    String? remoteId,
    String? characteristicUuid,
    List<int>? payload,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#writeCharacteristic, [
              remoteId,
              characteristicUuid,
              payload,
            ]),
            returnValue: _i4.Future<bool>.value(false),
            returnValueForMissingStub: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<List<int>?> writeAndWaitForResponse(
    String? remoteId,
    String? characteristicUuid,
    List<int>? requestPayload, {
    Duration? timeout = const Duration(seconds: 30),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAndWaitForResponse,
              [remoteId, characteristicUuid, requestPayload],
              {#timeout: timeout},
            ),
            returnValue: _i4.Future<List<int>?>.value(),
            returnValueForMissingStub: _i4.Future<List<int>?>.value(),
          )
          as _i4.Future<List<int>?>);

  @override
  _i4.Future<void> saveConnection(int? fromNodeId, int? toNodeId) =>
      (super.noSuchMethod(
            Invocation.method(#saveConnection, [fromNodeId, toNodeId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [NodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeRepository extends _i1.Mock implements _i8.NodeRepository {
  @override
  _i4.Stream<List<_i9.Node>> observeNodes() =>
      (super.noSuchMethod(
            Invocation.method(#observeNodes, []),
            returnValue: _i4.Stream<List<_i9.Node>>.empty(),
            returnValueForMissingStub: _i4.Stream<List<_i9.Node>>.empty(),
          )
          as _i4.Stream<List<_i9.Node>>);

  @override
  _i4.Future<_i9.Node?> getNodeById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNodeById, [id]),
            returnValue: _i4.Future<_i9.Node?>.value(),
            returnValueForMissingStub: _i4.Future<_i9.Node?>.value(),
          )
          as _i4.Future<_i9.Node?>);

  @override
  _i4.Future<_i9.Node?> getNodeByBleAddress(String? bleAddress) =>
      (super.noSuchMethod(
            Invocation.method(#getNodeByBleAddress, [bleAddress]),
            returnValue: _i4.Future<_i9.Node?>.value(),
            returnValueForMissingStub: _i4.Future<_i9.Node?>.value(),
          )
          as _i4.Future<_i9.Node?>);

  @override
  _i4.Future<_i9.Node?> getNodeByDeviceUuid(String? deviceUuid) =>
      (super.noSuchMethod(
            Invocation.method(#getNodeByDeviceUuid, [deviceUuid]),
            returnValue: _i4.Future<_i9.Node?>.value(),
            returnValueForMissingStub: _i4.Future<_i9.Node?>.value(),
          )
          as _i4.Future<_i9.Node?>);

  @override
  _i4.Future<_i9.Node?> getNodeByRemoteRef(String? remoteRef) =>
      (super.noSuchMethod(
            Invocation.method(#getNodeByRemoteRef, [remoteRef]),
            returnValue: _i4.Future<_i9.Node?>.value(),
            returnValueForMissingStub: _i4.Future<_i9.Node?>.value(),
          )
          as _i4.Future<_i9.Node?>);

  @override
  _i4.Future<_i9.Node?> getSelfNode() =>
      (super.noSuchMethod(
            Invocation.method(#getSelfNode, []),
            returnValue: _i4.Future<_i9.Node?>.value(),
            returnValueForMissingStub: _i4.Future<_i9.Node?>.value(),
          )
          as _i4.Future<_i9.Node?>);

  @override
  _i4.Future<void> upsertNode(_i9.Node? node) =>
      (super.noSuchMethod(
            Invocation.method(#upsertNode, [node]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i9.Node?> reconcileNodeIdentity(
    int? nodeId, {
    required String? deviceUuid,
    required String? name,
    required String? color,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #reconcileNodeIdentity,
              [nodeId],
              {#deviceUuid: deviceUuid, #name: name, #color: color},
            ),
            returnValue: _i4.Future<_i9.Node?>.value(),
            returnValueForMissingStub: _i4.Future<_i9.Node?>.value(),
          )
          as _i4.Future<_i9.Node?>);

  @override
  _i4.Future<void> updateNodeMetadata(int? id, {String? name, String? color}) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateNodeMetadata,
              [id],
              {#name: name, #color: color},
            ),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllNodes() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllNodes, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i10.UserRepository {
  @override
  _i4.Future<_i11.User?> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i4.Future<_i11.User?>.value(),
            returnValueForMissingStub: _i4.Future<_i11.User?>.value(),
          )
          as _i4.Future<_i11.User?>);

  @override
  _i4.Future<void> updateName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updateName, [name]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateColor(String? color) =>
      (super.noSuchMethod(
            Invocation.method(#updateColor, [color]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> createUser(_i11.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [user]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setLocalNodeId(int? nodeId) =>
      (super.noSuchMethod(
            Invocation.method(#setLocalNodeId, [nodeId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [ActiveGraphExchangeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockActiveGraphExchangeService extends _i1.Mock
    implements _i12.ActiveGraphExchangeService {
  @override
  Set<String> get activeRemoteIds =>
      (super.noSuchMethod(
            Invocation.getter(#activeRemoteIds),
            returnValue: <String>{},
            returnValueForMissingStub: <String>{},
          )
          as Set<String>);

  @override
  _i4.Future<void> markConnected(String? remoteId) =>
      (super.noSuchMethod(
            Invocation.method(#markConnected, [remoteId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markDisconnected(String? remoteId) =>
      (super.noSuchMethod(
            Invocation.method(#markDisconnected, [remoteId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clear() =>
      (super.noSuchMethod(
            Invocation.method(#clear, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> publishCurrentSnapshot() =>
      (super.noSuchMethod(
            Invocation.method(#publishCurrentSnapshot, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.NodosGraphPayload> buildCurrentPayload() =>
      (super.noSuchMethod(
            Invocation.method(#buildCurrentPayload, []),
            returnValue: _i4.Future<_i2.NodosGraphPayload>.value(
              _FakeNodosGraphPayload_0(
                this,
                Invocation.method(#buildCurrentPayload, []),
              ),
            ),
            returnValueForMissingStub: _i4.Future<_i2.NodosGraphPayload>.value(
              _FakeNodosGraphPayload_0(
                this,
                Invocation.method(#buildCurrentPayload, []),
              ),
            ),
          )
          as _i4.Future<_i2.NodosGraphPayload>);
}
