// Mocks generated by Mockito 5.4.6 from annotations
// in frontend_mobile_nodos_app/test/features/nodes/data/repositories/node_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:frontend_mobile_nodos_app/features/nodes/data/datasources/node_local_datasource.dart'
    as _i2;
import 'package:frontend_mobile_nodos_app/features/nodes/domain/entities/node.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NodeLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeLocalDataSource extends _i1.Mock
    implements _i2.NodeLocalDataSource {
  @override
  _i3.Stream<List<_i4.Node>> watchNodes() =>
      (super.noSuchMethod(
            Invocation.method(#watchNodes, []),
            returnValue: _i3.Stream<List<_i4.Node>>.empty(),
            returnValueForMissingStub: _i3.Stream<List<_i4.Node>>.empty(),
          )
          as _i3.Stream<List<_i4.Node>>);

  @override
  _i3.Future<_i4.Node?> getNodeById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNodeById, [id]),
            returnValue: _i3.Future<_i4.Node?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.Node?>.value(),
          )
          as _i3.Future<_i4.Node?>);

  @override
  _i3.Future<void> upsertNode(_i4.Node? node) =>
      (super.noSuchMethod(
            Invocation.method(#upsertNode, [node]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteNode(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNode, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAllNodes() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllNodes, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i4.Node?> getNodeByBleAddress(String? bleAddress) =>
      (super.noSuchMethod(
            Invocation.method(#getNodeByBleAddress, [bleAddress]),
            returnValue: _i3.Future<_i4.Node?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.Node?>.value(),
          )
          as _i3.Future<_i4.Node?>);
}
