// Mocks generated by Mockito 5.4.6 from annotations
// in frontend_mobile_nodos_app/test/features/user/presentation/bloc/user_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:frontend_mobile_nodos_app/core/errors/failures.dart' as _i6;
import 'package:frontend_mobile_nodos_app/core/usecases/usecase.dart' as _i8;
import 'package:frontend_mobile_nodos_app/features/user/domain/entities/user.dart'
    as _i7;
import 'package:frontend_mobile_nodos_app/features/user/domain/repositories/user_repository.dart'
    as _i2;
import 'package:frontend_mobile_nodos_app/features/user/domain/usecases/get_user_profile.dart'
    as _i4;
import 'package:frontend_mobile_nodos_app/features/user/domain/usecases/update_user_color.dart'
    as _i10;
import 'package:frontend_mobile_nodos_app/features/user/domain/usecases/update_user_name.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserRepository_0 extends _i1.SmartFake
    implements _i2.UserRepository {
  _FakeUserRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetUserProfile].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserProfile extends _i1.Mock implements _i4.GetUserProfile {
  @override
  _i2.UserRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeUserRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeUserRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.UserRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.User>> call(_i8.NoParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, _i7.User>>.value(
              _FakeEither_1<_i6.Failure, _i7.User>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.Either<_i6.Failure, _i7.User>>.value(
                  _FakeEither_1<_i6.Failure, _i7.User>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, _i7.User>>);
}

/// A class which mocks [UpdateUserName].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUserName extends _i1.Mock implements _i9.UpdateUserName {
  @override
  _i2.UserRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeUserRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeUserRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.UserRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
    _i9.UpdateUserNameParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.Either<_i6.Failure, void>>.value(
                  _FakeEither_1<_i6.Failure, void>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [UpdateUserColor].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUserColor extends _i1.Mock implements _i10.UpdateUserColor {
  @override
  _i2.UserRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeUserRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeUserRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.UserRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
    _i10.UpdateUserColorParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.Either<_i6.Failure, void>>.value(
                  _FakeEither_1<_i6.Failure, void>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i2.UserRepository {
  @override
  _i5.Future<_i7.User?> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i5.Future<_i7.User?>.value(),
            returnValueForMissingStub: _i5.Future<_i7.User?>.value(),
          )
          as _i5.Future<_i7.User?>);

  @override
  _i5.Future<void> updateName(String? name) =>
      (super.noSuchMethod(
            Invocation.method(#updateName, [name]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateColor(String? color) =>
      (super.noSuchMethod(
            Invocation.method(#updateColor, [color]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> createUser(_i7.User? user) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [user]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}
