// Mocks generated by Mockito 5.4.6 from annotations
// in frontend_mobile_nodos_app/test/features/nodes/presentation/bloc/node_list_bloc_sync_ble_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:frontend_mobile_nodos_app/core/errors/failures.dart' as _i8;
import 'package:frontend_mobile_nodos_app/features/nodes/domain/entities/node.dart'
    as _i6;
import 'package:frontend_mobile_nodos_app/features/nodes/domain/repositories/node_repository.dart'
    as _i2;
import 'package:frontend_mobile_nodos_app/features/nodes/domain/usecases/observe_nodes.dart'
    as _i4;
import 'package:frontend_mobile_nodos_app/features/nodes/domain/usecases/update_node_metadata.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNodeRepository_0 extends _i1.SmartFake
    implements _i2.NodeRepository {
  _FakeNodeRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ObserveNodes].
///
/// See the documentation for Mockito's code generation for more information.
class MockObserveNodes extends _i1.Mock implements _i4.ObserveNodes {
  @override
  _i2.NodeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNodeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeNodeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.NodeRepository);

  @override
  _i5.Stream<List<_i6.Node>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Stream<List<_i6.Node>>.empty(),
            returnValueForMissingStub: _i5.Stream<List<_i6.Node>>.empty(),
          )
          as _i5.Stream<List<_i6.Node>>);
}

/// A class which mocks [UpdateNodeMetadata].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateNodeMetadata extends _i1.Mock
    implements _i7.UpdateNodeMetadata {
  @override
  _i2.NodeRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeNodeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeNodeRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.NodeRepository);

  @override
  _i5.Future<_i3.Either<_i8.Failure, void>> call(
    _i7.UpdateNodeMetadataParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i8.Failure, void>>.value(
              _FakeEither_1<_i8.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
            returnValueForMissingStub:
                _i5.Future<_i3.Either<_i8.Failure, void>>.value(
                  _FakeEither_1<_i8.Failure, void>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i8.Failure, void>>);
}

/// A class which mocks [NodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeRepository extends _i1.Mock implements _i2.NodeRepository {
  @override
  _i5.Stream<List<_i6.Node>> observeNodes() =>
      (super.noSuchMethod(
            Invocation.method(#observeNodes, []),
            returnValue: _i5.Stream<List<_i6.Node>>.empty(),
            returnValueForMissingStub: _i5.Stream<List<_i6.Node>>.empty(),
          )
          as _i5.Stream<List<_i6.Node>>);

  @override
  _i5.Future<_i6.Node?> getNodeById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNodeById, [id]),
            returnValue: _i5.Future<_i6.Node?>.value(),
            returnValueForMissingStub: _i5.Future<_i6.Node?>.value(),
          )
          as _i5.Future<_i6.Node?>);

  @override
  _i5.Future<void> upsertNode(_i6.Node? node) =>
      (super.noSuchMethod(
            Invocation.method(#upsertNode, [node]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> updateNodeMetadata(int? id, {String? name, String? color}) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateNodeMetadata,
              [id],
              {#name: name, #color: color},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearAllNodes() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllNodes, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i6.Node?> getNodeByBleAddress(String? bleAddress) =>
      (super.noSuchMethod(
            Invocation.method(#getNodeByBleAddress, [bleAddress]),
            returnValue: _i5.Future<_i6.Node?>.value(),
            returnValueForMissingStub: _i5.Future<_i6.Node?>.value(),
          )
          as _i5.Future<_i6.Node?>);
}
