// Mocks generated by Mockito 5.4.6 from annotations
// in frontend_mobile_nodos_app/test/features/history/presentation/bloc/history_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:frontend_mobile_nodos_app/core/errors/failures.dart' as _i5;
import 'package:frontend_mobile_nodos_app/features/history/domain/entities/history_stats.dart'
    as _i10;
import 'package:frontend_mobile_nodos_app/features/history/domain/entities/scan_session.dart'
    as _i6;
import 'package:frontend_mobile_nodos_app/features/history/domain/entities/session_node.dart'
    as _i8;
import 'package:frontend_mobile_nodos_app/features/history/domain/usecases/get_history_stats.dart'
    as _i9;
import 'package:frontend_mobile_nodos_app/features/history/domain/usecases/get_scan_sessions.dart'
    as _i3;
import 'package:frontend_mobile_nodos_app/features/history/domain/usecases/get_session_detail.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetScanSessions].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetScanSessions extends _i1.Mock implements _i3.GetScanSessions {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ScanSession>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ScanSession>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ScanSession>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ScanSession>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ScanSession>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ScanSession>>>);
}

/// A class which mocks [GetSessionDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetSessionDetail extends _i1.Mock implements _i7.GetSessionDetail {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i8.SessionNode>>> call(
    _i7.GetSessionDetailParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i8.SessionNode>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i8.SessionNode>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i8.SessionNode>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i8.SessionNode>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i8.SessionNode>>>);
}

/// A class which mocks [GetHistoryStats].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetHistoryStats extends _i1.Mock implements _i9.GetHistoryStats {
  @override
  _i4.Future<_i2.Either<_i5.Failure, _i10.HistoryStats>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i10.HistoryStats>>.value(
                  _FakeEither_0<_i5.Failure, _i10.HistoryStats>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i10.HistoryStats>>.value(
                  _FakeEither_0<_i5.Failure, _i10.HistoryStats>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i10.HistoryStats>>);
}
