// Mocks generated by Mockito 5.4.6 from annotations
// in frontend_mobile_nodos_app/test/features/history/domain/usecases/get_session_detail_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:frontend_mobile_nodos_app/core/errors/failures.dart' as _i5;
import 'package:frontend_mobile_nodos_app/features/history/domain/entities/history_stats.dart'
    as _i8;
import 'package:frontend_mobile_nodos_app/features/history/domain/entities/scan_session.dart'
    as _i6;
import 'package:frontend_mobile_nodos_app/features/history/domain/entities/session_node.dart'
    as _i7;
import 'package:frontend_mobile_nodos_app/features/history/domain/repositories/history_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HistoryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryRepository extends _i1.Mock implements _i3.HistoryRepository {
  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.ScanSession>>> getSessions() =>
      (super.noSuchMethod(
            Invocation.method(#getSessions, []),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ScanSession>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ScanSession>>(
                    this,
                    Invocation.method(#getSessions, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i6.ScanSession>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i6.ScanSession>>(
                    this,
                    Invocation.method(#getSessions, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ScanSession>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i7.SessionNode>>> getSessionDetail(
    int? sessionId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getSessionDetail, [sessionId]),
            returnValue:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i7.SessionNode>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i7.SessionNode>>(
                    this,
                    Invocation.method(#getSessionDetail, [sessionId]),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<
                  _i2.Either<_i5.Failure, List<_i7.SessionNode>>
                >.value(
                  _FakeEither_0<_i5.Failure, List<_i7.SessionNode>>(
                    this,
                    Invocation.method(#getSessionDetail, [sessionId]),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i7.SessionNode>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i8.HistoryStats>> getStats() =>
      (super.noSuchMethod(
            Invocation.method(#getStats, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, _i8.HistoryStats>>.value(
                  _FakeEither_0<_i5.Failure, _i8.HistoryStats>(
                    this,
                    Invocation.method(#getStats, []),
                  ),
                ),
            returnValueForMissingStub:
                _i4.Future<_i2.Either<_i5.Failure, _i8.HistoryStats>>.value(
                  _FakeEither_0<_i5.Failure, _i8.HistoryStats>(
                    this,
                    Invocation.method(#getStats, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i8.HistoryStats>>);
}
