// Mocks generated by Mockito from annotations
// in frontend_mobile_nodos_app/test/features/onboarding/presentation/pages/onboarding_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i10;

import 'package:bloc/bloc.dart' as _i12;
import 'package:frontend_mobile_nodos_app/features/ble/domain/repositories/ble_repository.dart'
    as _i2;
import 'package:frontend_mobile_nodos_app/features/ble/presentation/bloc/ble_bloc.dart'
    as _i9;
import 'package:frontend_mobile_nodos_app/features/ble/presentation/bloc/ble_event.dart'
    as _i11;
import 'package:frontend_mobile_nodos_app/features/ble/presentation/bloc/ble_state.dart'
    as _i3;
import 'package:frontend_mobile_nodos_app/features/nodes/domain/usecases/ensure_local_node.dart'
    as _i7;
import 'package:frontend_mobile_nodos_app/features/user/domain/usecases/get_user_profile.dart'
    as _i4;
import 'package:frontend_mobile_nodos_app/features/user/domain/usecases/update_user_color.dart'
    as _i6;
import 'package:frontend_mobile_nodos_app/features/user/domain/usecases/update_user_name.dart'
    as _i5;
import 'package:frontend_mobile_nodos_app/features/user/presentation/bloc/user_bloc.dart'
    as _i8;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBleRepository_0 extends _i1.SmartFake implements _i2.BleRepository {
  _FakeBleRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBleState_1 extends _i1.SmartFake implements _i3.BleState {
  _FakeBleState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetUserProfile_2 extends _i1.SmartFake
    implements _i4.GetUserProfile {
  _FakeGetUserProfile_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateUserName_3 extends _i1.SmartFake
    implements _i5.UpdateUserName {
  _FakeUpdateUserName_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateUserColor_4 extends _i1.SmartFake
    implements _i6.UpdateUserColor {
  _FakeUpdateUserColor_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEnsureLocalNode_5 extends _i1.SmartFake
    implements _i7.EnsureLocalNode {
  _FakeEnsureLocalNode_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserState_6 extends _i1.SmartFake implements _i8.UserState {
  _FakeUserState_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BleBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleBloc extends _i1.Mock implements _i9.BleBloc {
  @override
  _i2.BleRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeBleRepository_0(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeBleRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.BleRepository);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i3.BleState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeBleState_1(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeBleState_1(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i3.BleState);

  @override
  _i10.Stream<_i3.BleState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i10.Stream<_i3.BleState>.empty(),
            returnValueForMissingStub: _i10.Stream<_i3.BleState>.empty(),
          )
          as _i10.Stream<_i3.BleState>);

  @override
  _i10.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void add(_i11.BleEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i11.BleEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i3.BleState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i11.BleEvent>(
    _i12.EventHandler<E, _i3.BleState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(_i12.Transition<_i11.BleEvent, _i3.BleState>? transition) =>
      super.noSuchMethod(
        Invocation.method(#onTransition, [transition]),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(_i11.BleEvent? event, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#onDone, [event, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i12.Change<_i3.BleState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserBloc extends _i1.Mock implements _i8.UserBloc {
  @override
  _i4.GetUserProfile get getProfile =>
      (super.noSuchMethod(
            Invocation.getter(#getProfile),
            returnValue: _FakeGetUserProfile_2(
              this,
              Invocation.getter(#getProfile),
            ),
            returnValueForMissingStub: _FakeGetUserProfile_2(
              this,
              Invocation.getter(#getProfile),
            ),
          )
          as _i4.GetUserProfile);

  @override
  _i5.UpdateUserName get updateName =>
      (super.noSuchMethod(
            Invocation.getter(#updateName),
            returnValue: _FakeUpdateUserName_3(
              this,
              Invocation.getter(#updateName),
            ),
            returnValueForMissingStub: _FakeUpdateUserName_3(
              this,
              Invocation.getter(#updateName),
            ),
          )
          as _i5.UpdateUserName);

  @override
  _i6.UpdateUserColor get updateColor =>
      (super.noSuchMethod(
            Invocation.getter(#updateColor),
            returnValue: _FakeUpdateUserColor_4(
              this,
              Invocation.getter(#updateColor),
            ),
            returnValueForMissingStub: _FakeUpdateUserColor_4(
              this,
              Invocation.getter(#updateColor),
            ),
          )
          as _i6.UpdateUserColor);

  @override
  _i7.EnsureLocalNode get ensureLocalNode =>
      (super.noSuchMethod(
            Invocation.getter(#ensureLocalNode),
            returnValue: _FakeEnsureLocalNode_5(
              this,
              Invocation.getter(#ensureLocalNode),
            ),
            returnValueForMissingStub: _FakeEnsureLocalNode_5(
              this,
              Invocation.getter(#ensureLocalNode),
            ),
          )
          as _i7.EnsureLocalNode);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.UserState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeUserState_6(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeUserState_6(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i8.UserState);

  @override
  _i10.Stream<_i8.UserState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i10.Stream<_i8.UserState>.empty(),
            returnValueForMissingStub: _i10.Stream<_i8.UserState>.empty(),
          )
          as _i10.Stream<_i8.UserState>);

  @override
  void add(_i8.UserEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i8.UserEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i8.UserState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i8.UserEvent>(
    _i12.EventHandler<E, _i8.UserState>? handler, {
    _i12.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i12.Transition<_i8.UserEvent, _i8.UserState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(_i8.UserEvent? event, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#onDone, [event, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  _i10.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i10.Future<void>.value(),
            returnValueForMissingStub: _i10.Future<void>.value(),
          )
          as _i10.Future<void>);

  @override
  void onChange(_i12.Change<_i8.UserState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
