// Mocks generated by Mockito from annotations
// in frontend_mobile_nodos_app/test/features/nodes/presentation/pages/home_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i18;

import 'package:bloc/bloc.dart' as _i19;
import 'package:frontend_mobile_nodos_app/features/ble/domain/entities/nodos_link_request.dart'
    as _i21;
import 'package:frontend_mobile_nodos_app/features/ble/domain/repositories/ble_connection_repository.dart'
    as _i9;
import 'package:frontend_mobile_nodos_app/features/ble/domain/repositories/ble_repository.dart'
    as _i5;
import 'package:frontend_mobile_nodos_app/features/ble/domain/repositories/remote_relation_repository.dart'
    as _i7;
import 'package:frontend_mobile_nodos_app/features/ble/presentation/bloc/ble_bloc.dart'
    as _i20;
import 'package:frontend_mobile_nodos_app/features/ble/presentation/bloc/ble_connection_bloc.dart'
    as _i25;
import 'package:frontend_mobile_nodos_app/features/ble/presentation/bloc/ble_event.dart'
    as _i22;
import 'package:frontend_mobile_nodos_app/features/ble/presentation/bloc/ble_state.dart'
    as _i10;
import 'package:frontend_mobile_nodos_app/features/nodes/domain/repositories/node_repository.dart'
    as _i8;
import 'package:frontend_mobile_nodos_app/features/nodes/domain/usecases/ensure_local_node.dart'
    as _i16;
import 'package:frontend_mobile_nodos_app/features/nodes/domain/usecases/observe_nodes.dart'
    as _i2;
import 'package:frontend_mobile_nodos_app/features/nodes/domain/usecases/update_node_metadata.dart'
    as _i3;
import 'package:frontend_mobile_nodos_app/features/nodes/presentation/bloc/node_list_bloc.dart'
    as _i4;
import 'package:frontend_mobile_nodos_app/features/scan_session/presentation/bloc/scan_session_bloc.dart'
    as _i12;
import 'package:frontend_mobile_nodos_app/features/user/domain/repositories/user_repository.dart'
    as _i6;
import 'package:frontend_mobile_nodos_app/features/user/domain/usecases/get_user_profile.dart'
    as _i13;
import 'package:frontend_mobile_nodos_app/features/user/domain/usecases/update_user_color.dart'
    as _i15;
import 'package:frontend_mobile_nodos_app/features/user/domain/usecases/update_user_name.dart'
    as _i14;
import 'package:frontend_mobile_nodos_app/features/user/presentation/bloc/user_bloc.dart'
    as _i17;
import 'package:frontend_mobile_nodos_app/features/visualization/presentation/bloc/visualization_bloc.dart'
    as _i23;
import 'package:frontend_mobile_nodos_app/features/visualization/presentation/bloc/visualization_event.dart'
    as _i24;
import 'package:frontend_mobile_nodos_app/features/visualization/presentation/bloc/visualization_state.dart'
    as _i11;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i26;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: experimental_member_use
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeObserveNodes_0 extends _i1.SmartFake implements _i2.ObserveNodes {
  _FakeObserveNodes_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateNodeMetadata_1 extends _i1.SmartFake
    implements _i3.UpdateNodeMetadata {
  _FakeUpdateNodeMetadata_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNodeListState_2 extends _i1.SmartFake implements _i4.NodeListState {
  _FakeNodeListState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBleRepository_3 extends _i1.SmartFake implements _i5.BleRepository {
  _FakeBleRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserRepository_4 extends _i1.SmartFake
    implements _i6.UserRepository {
  _FakeUserRepository_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoteRelationRepository_5 extends _i1.SmartFake
    implements _i7.RemoteRelationRepository {
  _FakeRemoteRelationRepository_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNodeRepository_6 extends _i1.SmartFake
    implements _i8.NodeRepository {
  _FakeNodeRepository_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBleConnectionRepository_7 extends _i1.SmartFake
    implements _i9.BleConnectionRepository {
  _FakeBleConnectionRepository_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBleState_8 extends _i1.SmartFake implements _i10.BleState {
  _FakeBleState_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVisualizationState_9 extends _i1.SmartFake
    implements _i11.VisualizationState {
  _FakeVisualizationState_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeScanSessionState_10 extends _i1.SmartFake
    implements _i12.ScanSessionState {
  _FakeScanSessionState_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetUserProfile_11 extends _i1.SmartFake
    implements _i13.GetUserProfile {
  _FakeGetUserProfile_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateUserName_12 extends _i1.SmartFake
    implements _i14.UpdateUserName {
  _FakeUpdateUserName_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateUserColor_13 extends _i1.SmartFake
    implements _i15.UpdateUserColor {
  _FakeUpdateUserColor_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEnsureLocalNode_14 extends _i1.SmartFake
    implements _i16.EnsureLocalNode {
  _FakeEnsureLocalNode_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserState_15 extends _i1.SmartFake implements _i17.UserState {
  _FakeUserState_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NodeListBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeListBloc extends _i1.Mock implements _i4.NodeListBloc {
  @override
  _i2.ObserveNodes get observeNodes =>
      (super.noSuchMethod(
            Invocation.getter(#observeNodes),
            returnValue: _FakeObserveNodes_0(
              this,
              Invocation.getter(#observeNodes),
            ),
            returnValueForMissingStub: _FakeObserveNodes_0(
              this,
              Invocation.getter(#observeNodes),
            ),
          )
          as _i2.ObserveNodes);

  @override
  _i3.UpdateNodeMetadata get updateNodeMetadata =>
      (super.noSuchMethod(
            Invocation.getter(#updateNodeMetadata),
            returnValue: _FakeUpdateNodeMetadata_1(
              this,
              Invocation.getter(#updateNodeMetadata),
            ),
            returnValueForMissingStub: _FakeUpdateNodeMetadata_1(
              this,
              Invocation.getter(#updateNodeMetadata),
            ),
          )
          as _i3.UpdateNodeMetadata);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.NodeListState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeNodeListState_2(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeNodeListState_2(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i4.NodeListState);

  @override
  _i18.Stream<_i4.NodeListState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i18.Stream<_i4.NodeListState>.empty(),
            returnValueForMissingStub: _i18.Stream<_i4.NodeListState>.empty(),
          )
          as _i18.Stream<_i4.NodeListState>);

  @override
  _i18.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  void add(_i4.NodeListEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i4.NodeListEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.NodeListState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i4.NodeListEvent>(
    _i19.EventHandler<E, _i4.NodeListState>? handler, {
    _i19.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i19.Transition<_i4.NodeListEvent, _i4.NodeListState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i4.NodeListEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i19.Change<_i4.NodeListState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BleBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleBloc extends _i1.Mock implements _i20.BleBloc {
  @override
  _i5.BleRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeBleRepository_3(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeBleRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.BleRepository);

  @override
  _i6.UserRepository get userRepository =>
      (super.noSuchMethod(
            Invocation.getter(#userRepository),
            returnValue: _FakeUserRepository_4(
              this,
              Invocation.getter(#userRepository),
            ),
            returnValueForMissingStub: _FakeUserRepository_4(
              this,
              Invocation.getter(#userRepository),
            ),
          )
          as _i6.UserRepository);

  @override
  _i7.RemoteRelationRepository get remoteRelationRepository =>
      (super.noSuchMethod(
            Invocation.getter(#remoteRelationRepository),
            returnValue: _FakeRemoteRelationRepository_5(
              this,
              Invocation.getter(#remoteRelationRepository),
            ),
            returnValueForMissingStub: _FakeRemoteRelationRepository_5(
              this,
              Invocation.getter(#remoteRelationRepository),
            ),
          )
          as _i7.RemoteRelationRepository);

  @override
  _i8.NodeRepository get nodeRepository =>
      (super.noSuchMethod(
            Invocation.getter(#nodeRepository),
            returnValue: _FakeNodeRepository_6(
              this,
              Invocation.getter(#nodeRepository),
            ),
            returnValueForMissingStub: _FakeNodeRepository_6(
              this,
              Invocation.getter(#nodeRepository),
            ),
          )
          as _i8.NodeRepository);

  @override
  _i9.BleConnectionRepository get connectionRepository =>
      (super.noSuchMethod(
            Invocation.getter(#connectionRepository),
            returnValue: _FakeBleConnectionRepository_7(
              this,
              Invocation.getter(#connectionRepository),
            ),
            returnValueForMissingStub: _FakeBleConnectionRepository_7(
              this,
              Invocation.getter(#connectionRepository),
            ),
          )
          as _i9.BleConnectionRepository);

  @override
  _i18.Stream<_i21.NodosLinkRequest> get linkRequests =>
      (super.noSuchMethod(
            Invocation.getter(#linkRequests),
            returnValue: _i18.Stream<_i21.NodosLinkRequest>.empty(),
            returnValueForMissingStub:
                _i18.Stream<_i21.NodosLinkRequest>.empty(),
          )
          as _i18.Stream<_i21.NodosLinkRequest>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i10.BleState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeBleState_8(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeBleState_8(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i10.BleState);

  @override
  _i18.Stream<_i10.BleState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i18.Stream<_i10.BleState>.empty(),
            returnValueForMissingStub: _i18.Stream<_i10.BleState>.empty(),
          )
          as _i18.Stream<_i10.BleState>);

  @override
  _i18.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  void add(_i22.BleEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i22.BleEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i10.BleState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i22.BleEvent>(
    _i19.EventHandler<E, _i10.BleState>? handler, {
    _i19.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i19.Transition<_i22.BleEvent, _i10.BleState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(_i22.BleEvent? event, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#onDone, [event, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i19.Change<_i10.BleState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [VisualizationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockVisualizationBloc extends _i1.Mock implements _i23.VisualizationBloc {
  @override
  bool get isBuilding =>
      (super.noSuchMethod(
            Invocation.getter(#isBuilding),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i11.VisualizationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeVisualizationState_9(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeVisualizationState_9(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i11.VisualizationState);

  @override
  _i18.Stream<_i11.VisualizationState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i18.Stream<_i11.VisualizationState>.empty(),
            returnValueForMissingStub:
                _i18.Stream<_i11.VisualizationState>.empty(),
          )
          as _i18.Stream<_i11.VisualizationState>);

  @override
  _i18.Future<void> processBuildRequest(
    _i24.BuildGraphRequested? event,
    _i19.Emitter<_i11.VisualizationState>? emit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#processBuildRequest, [event, emit]),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  _i18.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  void add(_i24.VisualizationEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i24.VisualizationEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i11.VisualizationState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i24.VisualizationEvent>(
    _i19.EventHandler<E, _i11.VisualizationState>? handler, {
    _i19.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i19.Transition<_i24.VisualizationEvent, _i11.VisualizationState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i24.VisualizationEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i19.Change<_i11.VisualizationState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BleConnectionBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleConnectionBloc extends _i1.Mock implements _i25.BleConnectionBloc {
  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i25.BleConnectionState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i26.dummyValue<_i25.BleConnectionState>(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _i26.dummyValue<_i25.BleConnectionState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i25.BleConnectionState);

  @override
  _i18.Stream<_i25.BleConnectionState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i18.Stream<_i25.BleConnectionState>.empty(),
            returnValueForMissingStub:
                _i18.Stream<_i25.BleConnectionState>.empty(),
          )
          as _i18.Stream<_i25.BleConnectionState>);

  @override
  _i18.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  void add(_i25.BleConnectionEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i25.BleConnectionEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i25.BleConnectionState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i25.BleConnectionEvent>(
    _i19.EventHandler<E, _i25.BleConnectionState>? handler, {
    _i19.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i19.Transition<_i25.BleConnectionEvent, _i25.BleConnectionState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i25.BleConnectionEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i19.Change<_i25.BleConnectionState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ScanSessionBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockScanSessionBloc extends _i1.Mock implements _i12.ScanSessionBloc {
  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i12.ScanSessionState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeScanSessionState_10(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeScanSessionState_10(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i12.ScanSessionState);

  @override
  _i18.Stream<_i12.ScanSessionState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i18.Stream<_i12.ScanSessionState>.empty(),
            returnValueForMissingStub:
                _i18.Stream<_i12.ScanSessionState>.empty(),
          )
          as _i18.Stream<_i12.ScanSessionState>);

  @override
  void add(_i12.ScanSessionEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i12.ScanSessionEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i12.ScanSessionState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i12.ScanSessionEvent>(
    _i19.EventHandler<E, _i12.ScanSessionState>? handler, {
    _i19.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i19.Transition<_i12.ScanSessionEvent, _i12.ScanSessionState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i12.ScanSessionEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i18.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  void onChange(_i19.Change<_i12.ScanSessionState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserBloc extends _i1.Mock implements _i17.UserBloc {
  @override
  _i13.GetUserProfile get getProfile =>
      (super.noSuchMethod(
            Invocation.getter(#getProfile),
            returnValue: _FakeGetUserProfile_11(
              this,
              Invocation.getter(#getProfile),
            ),
            returnValueForMissingStub: _FakeGetUserProfile_11(
              this,
              Invocation.getter(#getProfile),
            ),
          )
          as _i13.GetUserProfile);

  @override
  _i14.UpdateUserName get updateName =>
      (super.noSuchMethod(
            Invocation.getter(#updateName),
            returnValue: _FakeUpdateUserName_12(
              this,
              Invocation.getter(#updateName),
            ),
            returnValueForMissingStub: _FakeUpdateUserName_12(
              this,
              Invocation.getter(#updateName),
            ),
          )
          as _i14.UpdateUserName);

  @override
  _i15.UpdateUserColor get updateColor =>
      (super.noSuchMethod(
            Invocation.getter(#updateColor),
            returnValue: _FakeUpdateUserColor_13(
              this,
              Invocation.getter(#updateColor),
            ),
            returnValueForMissingStub: _FakeUpdateUserColor_13(
              this,
              Invocation.getter(#updateColor),
            ),
          )
          as _i15.UpdateUserColor);

  @override
  _i16.EnsureLocalNode get ensureLocalNode =>
      (super.noSuchMethod(
            Invocation.getter(#ensureLocalNode),
            returnValue: _FakeEnsureLocalNode_14(
              this,
              Invocation.getter(#ensureLocalNode),
            ),
            returnValueForMissingStub: _FakeEnsureLocalNode_14(
              this,
              Invocation.getter(#ensureLocalNode),
            ),
          )
          as _i16.EnsureLocalNode);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i17.UserState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeUserState_15(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeUserState_15(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i17.UserState);

  @override
  _i18.Stream<_i17.UserState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i18.Stream<_i17.UserState>.empty(),
            returnValueForMissingStub: _i18.Stream<_i17.UserState>.empty(),
          )
          as _i18.Stream<_i17.UserState>);

  @override
  void add(_i17.UserEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i17.UserEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i17.UserState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i17.UserEvent>(
    _i19.EventHandler<E, _i17.UserState>? handler, {
    _i19.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i19.Transition<_i17.UserEvent, _i17.UserState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(_i17.UserEvent? event, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#onDone, [event, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  _i18.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i18.Future<void>.value(),
            returnValueForMissingStub: _i18.Future<void>.value(),
          )
          as _i18.Future<void>);

  @override
  void onChange(_i19.Change<_i17.UserState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
