// Mocks generated by Mockito 5.4.6 from annotations
// in frontend_mobile_nodos_app/test/features/nodes/presentation/pages/home_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:flutter_bloc/flutter_bloc.dart' as _i10;
import 'package:frontend_mobile_nodos_app/features/ble/domain/repositories/ble_repository.dart'
    as _i5;
import 'package:frontend_mobile_nodos_app/features/ble/presentation/bloc/ble_bloc.dart'
    as _i11;
import 'package:frontend_mobile_nodos_app/features/ble/presentation/bloc/ble_connection_bloc.dart'
    as _i15;
import 'package:frontend_mobile_nodos_app/features/ble/presentation/bloc/ble_event.dart'
    as _i12;
import 'package:frontend_mobile_nodos_app/features/ble/presentation/bloc/ble_state.dart'
    as _i6;
import 'package:frontend_mobile_nodos_app/features/nodes/domain/usecases/observe_nodes.dart'
    as _i2;
import 'package:frontend_mobile_nodos_app/features/nodes/domain/usecases/update_node_metadata.dart'
    as _i3;
import 'package:frontend_mobile_nodos_app/features/nodes/presentation/bloc/node_list_bloc.dart'
    as _i4;
import 'package:frontend_mobile_nodos_app/features/scan_session/presentation/bloc/scan_session_bloc.dart'
    as _i8;
import 'package:frontend_mobile_nodos_app/features/visualization/presentation/bloc/visualization_bloc.dart'
    as _i13;
import 'package:frontend_mobile_nodos_app/features/visualization/presentation/bloc/visualization_event.dart'
    as _i14;
import 'package:frontend_mobile_nodos_app/features/visualization/presentation/bloc/visualization_state.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i16;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeObserveNodes_0 extends _i1.SmartFake implements _i2.ObserveNodes {
  _FakeObserveNodes_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateNodeMetadata_1 extends _i1.SmartFake
    implements _i3.UpdateNodeMetadata {
  _FakeUpdateNodeMetadata_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNodeListState_2 extends _i1.SmartFake implements _i4.NodeListState {
  _FakeNodeListState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBleRepository_3 extends _i1.SmartFake implements _i5.BleRepository {
  _FakeBleRepository_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBleState_4 extends _i1.SmartFake implements _i6.BleState {
  _FakeBleState_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVisualizationState_5 extends _i1.SmartFake
    implements _i7.VisualizationState {
  _FakeVisualizationState_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeScanSessionState_6 extends _i1.SmartFake
    implements _i8.ScanSessionState {
  _FakeScanSessionState_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NodeListBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeListBloc extends _i1.Mock implements _i4.NodeListBloc {
  @override
  _i2.ObserveNodes get observeNodes =>
      (super.noSuchMethod(
            Invocation.getter(#observeNodes),
            returnValue: _FakeObserveNodes_0(
              this,
              Invocation.getter(#observeNodes),
            ),
            returnValueForMissingStub: _FakeObserveNodes_0(
              this,
              Invocation.getter(#observeNodes),
            ),
          )
          as _i2.ObserveNodes);

  @override
  _i3.UpdateNodeMetadata get updateNodeMetadata =>
      (super.noSuchMethod(
            Invocation.getter(#updateNodeMetadata),
            returnValue: _FakeUpdateNodeMetadata_1(
              this,
              Invocation.getter(#updateNodeMetadata),
            ),
            returnValueForMissingStub: _FakeUpdateNodeMetadata_1(
              this,
              Invocation.getter(#updateNodeMetadata),
            ),
          )
          as _i3.UpdateNodeMetadata);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i4.NodeListState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeNodeListState_2(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeNodeListState_2(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i4.NodeListState);

  @override
  _i9.Stream<_i4.NodeListState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i4.NodeListState>.empty(),
            returnValueForMissingStub: _i9.Stream<_i4.NodeListState>.empty(),
          )
          as _i9.Stream<_i4.NodeListState>);

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void add(_i4.NodeListEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i4.NodeListEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i4.NodeListState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i4.NodeListEvent>(
    _i10.EventHandler<E, _i4.NodeListState>? handler, {
    _i10.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i10.Transition<_i4.NodeListEvent, _i4.NodeListState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i4.NodeListEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i10.Change<_i4.NodeListState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BleBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleBloc extends _i1.Mock implements _i11.BleBloc {
  @override
  _i5.BleRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeBleRepository_3(
              this,
              Invocation.getter(#repository),
            ),
            returnValueForMissingStub: _FakeBleRepository_3(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i5.BleRepository);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.BleState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeBleState_4(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeBleState_4(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i6.BleState);

  @override
  _i9.Stream<_i6.BleState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i6.BleState>.empty(),
            returnValueForMissingStub: _i9.Stream<_i6.BleState>.empty(),
          )
          as _i9.Stream<_i6.BleState>);

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void add(_i12.BleEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i12.BleEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i6.BleState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i12.BleEvent>(
    _i10.EventHandler<E, _i6.BleState>? handler, {
    _i10.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(_i10.Transition<_i12.BleEvent, _i6.BleState>? transition) =>
      super.noSuchMethod(
        Invocation.method(#onTransition, [transition]),
        returnValueForMissingStub: null,
      );

  @override
  void onDone(_i12.BleEvent? event, [Object? error, StackTrace? stackTrace]) =>
      super.noSuchMethod(
        Invocation.method(#onDone, [event, error, stackTrace]),
        returnValueForMissingStub: null,
      );

  @override
  void onChange(_i10.Change<_i6.BleState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [VisualizationBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockVisualizationBloc extends _i1.Mock implements _i13.VisualizationBloc {
  @override
  bool get isBuilding =>
      (super.noSuchMethod(
            Invocation.getter(#isBuilding),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i7.VisualizationState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeVisualizationState_5(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeVisualizationState_5(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i7.VisualizationState);

  @override
  _i9.Stream<_i7.VisualizationState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i7.VisualizationState>.empty(),
            returnValueForMissingStub:
                _i9.Stream<_i7.VisualizationState>.empty(),
          )
          as _i9.Stream<_i7.VisualizationState>);

  @override
  _i9.Future<void> processBuildRequest(
    _i14.BuildGraphRequested? event,
    _i10.Emitter<_i7.VisualizationState>? emit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#processBuildRequest, [event, emit]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void add(_i14.VisualizationEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i14.VisualizationEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i7.VisualizationState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i14.VisualizationEvent>(
    _i10.EventHandler<E, _i7.VisualizationState>? handler, {
    _i10.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i10.Transition<_i14.VisualizationEvent, _i7.VisualizationState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i14.VisualizationEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void onChange(_i10.Change<_i7.VisualizationState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BleConnectionBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockBleConnectionBloc extends _i1.Mock implements _i15.BleConnectionBloc {
  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i15.BleConnectionState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _i16.dummyValue<_i15.BleConnectionState>(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _i16.dummyValue<_i15.BleConnectionState>(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i15.BleConnectionState);

  @override
  _i9.Stream<_i15.BleConnectionState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i15.BleConnectionState>.empty(),
            returnValueForMissingStub:
                _i9.Stream<_i15.BleConnectionState>.empty(),
          )
          as _i9.Stream<_i15.BleConnectionState>);

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void add(_i15.BleConnectionEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i15.BleConnectionEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i15.BleConnectionState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i15.BleConnectionEvent>(
    _i10.EventHandler<E, _i15.BleConnectionState>? handler, {
    _i10.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i10.Transition<_i15.BleConnectionEvent, _i15.BleConnectionState>?
    transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i15.BleConnectionEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i10.Change<_i15.BleConnectionState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ScanSessionBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockScanSessionBloc extends _i1.Mock implements _i8.ScanSessionBloc {
  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.ScanSessionState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeScanSessionState_6(
              this,
              Invocation.getter(#state),
            ),
            returnValueForMissingStub: _FakeScanSessionState_6(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i8.ScanSessionState);

  @override
  _i9.Stream<_i8.ScanSessionState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i9.Stream<_i8.ScanSessionState>.empty(),
            returnValueForMissingStub: _i9.Stream<_i8.ScanSessionState>.empty(),
          )
          as _i9.Stream<_i8.ScanSessionState>);

  @override
  void add(_i8.ScanSessionEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i8.ScanSessionEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i8.ScanSessionState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i8.ScanSessionEvent>(
    _i10.EventHandler<E, _i8.ScanSessionState>? handler, {
    _i10.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i10.Transition<_i8.ScanSessionEvent, _i8.ScanSessionState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i8.ScanSessionEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i9.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  void onChange(_i10.Change<_i8.ScanSessionState>? change) =>
      super.noSuchMethod(
        Invocation.method(#onChange, [change]),
        returnValueForMissingStub: null,
      );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
