// Mocks generated by Mockito 5.4.6 from annotations
// in frontend_mobile_nodos_app/test/features/history/presentation/pages/stats_tab_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:frontend_mobile_nodos_app/features/history/domain/usecases/get_history_stats.dart'
    as _i4;
import 'package:frontend_mobile_nodos_app/features/history/domain/usecases/get_scan_sessions.dart'
    as _i2;
import 'package:frontend_mobile_nodos_app/features/history/domain/usecases/get_session_detail.dart'
    as _i3;
import 'package:frontend_mobile_nodos_app/features/history/presentation/bloc/history_bloc.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetScanSessions_0 extends _i1.SmartFake
    implements _i2.GetScanSessions {
  _FakeGetScanSessions_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetSessionDetail_1 extends _i1.SmartFake
    implements _i3.GetSessionDetail {
  _FakeGetSessionDetail_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetHistoryStats_2 extends _i1.SmartFake
    implements _i4.GetHistoryStats {
  _FakeGetHistoryStats_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHistoryState_3 extends _i1.SmartFake implements _i5.HistoryState {
  _FakeHistoryState_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HistoryBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockHistoryBloc extends _i1.Mock implements _i5.HistoryBloc {
  @override
  _i2.GetScanSessions get getScanSessions =>
      (super.noSuchMethod(
            Invocation.getter(#getScanSessions),
            returnValue: _FakeGetScanSessions_0(
              this,
              Invocation.getter(#getScanSessions),
            ),
            returnValueForMissingStub: _FakeGetScanSessions_0(
              this,
              Invocation.getter(#getScanSessions),
            ),
          )
          as _i2.GetScanSessions);

  @override
  _i3.GetSessionDetail get getSessionDetail =>
      (super.noSuchMethod(
            Invocation.getter(#getSessionDetail),
            returnValue: _FakeGetSessionDetail_1(
              this,
              Invocation.getter(#getSessionDetail),
            ),
            returnValueForMissingStub: _FakeGetSessionDetail_1(
              this,
              Invocation.getter(#getSessionDetail),
            ),
          )
          as _i3.GetSessionDetail);

  @override
  _i4.GetHistoryStats get getHistoryStats =>
      (super.noSuchMethod(
            Invocation.getter(#getHistoryStats),
            returnValue: _FakeGetHistoryStats_2(
              this,
              Invocation.getter(#getHistoryStats),
            ),
            returnValueForMissingStub: _FakeGetHistoryStats_2(
              this,
              Invocation.getter(#getHistoryStats),
            ),
          )
          as _i4.GetHistoryStats);

  @override
  bool get isClosed =>
      (super.noSuchMethod(
            Invocation.getter(#isClosed),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i5.HistoryState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeHistoryState_3(this, Invocation.getter(#state)),
            returnValueForMissingStub: _FakeHistoryState_3(
              this,
              Invocation.getter(#state),
            ),
          )
          as _i5.HistoryState);

  @override
  _i6.Stream<_i5.HistoryState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i5.HistoryState>.empty(),
            returnValueForMissingStub: _i6.Stream<_i5.HistoryState>.empty(),
          )
          as _i6.Stream<_i5.HistoryState>);

  @override
  void add(_i5.HistoryEvent? event) => super.noSuchMethod(
    Invocation.method(#add, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void onEvent(_i5.HistoryEvent? event) => super.noSuchMethod(
    Invocation.method(#onEvent, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i5.HistoryState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void on<E extends _i5.HistoryEvent>(
    _i7.EventHandler<E, _i5.HistoryState>? handler, {
    _i7.EventTransformer<E>? transformer,
  }) => super.noSuchMethod(
    Invocation.method(#on, [handler], {#transformer: transformer}),
    returnValueForMissingStub: null,
  );

  @override
  void onTransition(
    _i7.Transition<_i5.HistoryEvent, _i5.HistoryState>? transition,
  ) => super.noSuchMethod(
    Invocation.method(#onTransition, [transition]),
    returnValueForMissingStub: null,
  );

  @override
  void onDone(
    _i5.HistoryEvent? event, [
    Object? error,
    StackTrace? stackTrace,
  ]) => super.noSuchMethod(
    Invocation.method(#onDone, [event, error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onChange(_i7.Change<_i5.HistoryState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );
}
