// Mocks generated by Mockito 5.4.6 from annotations
// in frontend_mobile_nodos_app/test/features/visualization/data/repositories/graph_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:frontend_mobile_nodos_app/features/nodes/domain/entities/node.dart'
    as _i4;
import 'package:frontend_mobile_nodos_app/features/nodes/domain/repositories/node_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [NodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockNodeRepository extends _i1.Mock implements _i2.NodeRepository {
  @override
  _i3.Stream<List<_i4.Node>> observeNodes() =>
      (super.noSuchMethod(
            Invocation.method(#observeNodes, []),
            returnValue: _i3.Stream<List<_i4.Node>>.empty(),
            returnValueForMissingStub: _i3.Stream<List<_i4.Node>>.empty(),
          )
          as _i3.Stream<List<_i4.Node>>);

  @override
  _i3.Future<_i4.Node?> getNodeById(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#getNodeById, [id]),
            returnValue: _i3.Future<_i4.Node?>.value(),
            returnValueForMissingStub: _i3.Future<_i4.Node?>.value(),
          )
          as _i3.Future<_i4.Node?>);

  @override
  _i3.Future<void> upsertNode(_i4.Node? node) =>
      (super.noSuchMethod(
            Invocation.method(#upsertNode, [node]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateNodeMetadata(int? id, {String? name, String? color}) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateNodeMetadata,
              [id],
              {#name: name, #color: color},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
